# Generated by Django 4.0.5 on 2022-06-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_country_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Accepted', 'Accepted'), ('New', 'New'), ('Cancelled', 'Cancelled')], default='New', max_length=15),
        ),
    ]
