# Generated by Django 4.0.5 on 2022-06-23 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'product gallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
