# Generated by Django 4.0.5 on 2022-06-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_product_name_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nishad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
    ]
