# Generated by Django 4.0.5 on 2022-06-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_nishad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nishad',
        ),
    ]
