# Generated by Django 4.0.5 on 2022-07-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='slug',
        ),
    ]
